reanahub/reana-workflow-engine-cwl

AUTHORS.rst
README.rst
docs/authors.rst
docs/changes.rst
docs/conf.py
docs/contributing.rst
docs/gettingstarted.rst
docs/index.rst
docs/introduction.rst
docs/license.rst

* Enhances documentation structure, updates author list, updates short
description and feature list.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

 docs: better structure

---

.travis.yml
run-tests.sh

* Initial release of the Travis CI recipe. (closes #22)
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

travis: initial release

---

reana_workflow_engine_cwl/cwl_reana.py

Closes #14 , closes #16 , closes #9

Fixes for full CWL conformance

---

AUTHORS.rst
CHANGES.rst
docs/developerguide.rst
reana_workflow_engine_cwl/version.py

- 88e585621e87299ff3a9802a93155ac5430c91c2 release: v0.2.0
- 6baa2e275e25f6c4d66fde0727f55a5b3be86a3f docs: update information about conformance testing

release: v0.2.0

---

.travis.yml
Dockerfile
reana_workflow_engine_cwl/database.py
reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/tasks.py
requirements-dev.txt
setup.py

global: models imported from reana-commons

---

AUTHORS.rst
reana_workflow_engine_cwl/version.py

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

docs: author ORCID links

---

setup.py

* Fixes `KeyError async` error on startup.
Closes #41 

installation: pin kombu==4.1.0

---

reana_workflow_engine_cwl/config.py
reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/database.py
reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/pipeline.py
reana_workflow_engine_cwl/poll.py
reana_workflow_engine_cwl/tasks.py
reana_workflow_engine_cwl/utils.py
setup.py

* Publishes workflow status to message broker, instead of accessing the DB.

tasks: publish workflow status to message broker

---

reana_workflow_engine_cwl/config.py
reana_workflow_engine_cwl/main.py

tasks: use single working directory

---

reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/httpclient.py
reana_workflow_engine_cwl/main.py

Connects https://github.com/reanahub/reana-commons/issues/24
Closes https://github.com/reanahub/reana-workflow-engine-serial/issues/15

cwl_runner: progress status renaming

---

reana_workflow_engine_cwl/tasks.py
setup.py

installation: addition of reana-commons

---

Dockerfile

Dockerfile: change install order of reana-commons

---

CHANGES.rst
Dockerfile
reana_workflow_engine_cwl/celery_zeromq.py
reana_workflow_engine_cwl/celeryapp.py
reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/database.py
reana_workflow_engine_cwl/httpclient.py
reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/pipeline.py
reana_workflow_engine_cwl/poll.py
reana_workflow_engine_cwl/tasks.py
reana_workflow_engine_cwl/version.py
reana_workflow_engine_cwl/zeromq_tracker.py
requirements-dev.txt
run-tests.sh
setup.py

global: docstring additions and fixes for release

---

reana_workflow_engine_cwl/context.py
reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/httpclient.py
reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/pipeline.py
reana_workflow_engine_cwl/tasks.py
setup.py

* Closes reanahub/reana-client#169.

installation: upgrade cwltool

---

reana_workflow_engine_cwl/tasks.py
setup.py

Connects reanahub/reana-workflow-controller#131.

publisher: use Kombu publisher

---

AUTHORS.rst
CHANGES.rst
reana_workflow_engine_cwl/version.py
setup.py

release: v0.4.0

---

Dockerfile
reana_workflow_engine_cwl/celeryapp.py
reana_workflow_engine_cwl/tasks.py

Connects reanahub/reana-client#194.

tasks: add stop_workflow task from reana_commons

---

reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/tasks.py
setup.py

global: workflow engine independent of celery

---

reana_workflow_engine_cwl/config.py

config: MOUNT_CVMFS as string

---

reana_workflow_engine_cwl/config.py
reana_workflow_engine_cwl/cwl_reana.py
setup.py

Connect https://github.com/reanahub/reana-cluster/issues/154

config: cvmfs_mounts boolean

---

reana_workflow_engine_cwl/version.py
setup.py

installation: reana-commons with kubernetes

---

reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/main.py
setup.py

global: setting umask to 002

---

reana_workflow_engine_cwl/config.py
reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/pipeline.py
reana_workflow_engine_cwl/tasks.py

logging: logging format from R-Commons

---

AUTHORS.rst
CHANGES.rst
README.rst
docs/conf.py
reana_workflow_engine_cwl/version.py
setup.py

release: v0.5.0

---

reana_workflow_engine_cwl/cwl_reana.py

cwl_reana: deletes get_logs api call to RJC

---

reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/main.py

main: fixes output dir

---

.travis.yml
AUTHORS.rst
Dockerfile
reana_workflow_engine_cwl/main.py
setup.py

* Migrated to `python 3.6`
* Closes #74
Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>

cwltool: upgrade

---

reana_workflow_engine_cwl/cwl_reana.py
setup.py

cwl_reana: adds kerberos field

---

reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/database.py

* Removed undefined logging variables
* Added cwl response codes
* Closes #116
Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>

cwl: fixed error logs

---

reana_workflow_engine_cwl/config.py
reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/pipeline.py
reana_workflow_engine_cwl/tasks.py

Also refactored to more pythonic `fstrings`.

cwl: workflow status

---

reana_workflow_engine_cwl/main.py

* Closes #45
Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>

logs: reduce cwl verbosity

---

reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/tasks.py

* Added a function to parse str dict values to int
* Closes #118
Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>

cwl: parse CLI parameters as int

---

setup.py

* Upgrades version of `cwltool` to 1.0.20191022103248.
(addresses reanahub/reana-client#329)
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

cwltool: 1.0.20191022103248

---

reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/pipeline.py
reana_workflow_engine_cwl/poll.py

* Addresses reanahub/reana-workflow-controller/issues/269

cwl_reana: deletes experiment field from job request

---

reana_workflow_engine_cwl/version.py
setup.py

Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

version: post-release bump

---

reana_workflow_engine_cwl/cwl_reana.py

* Addresses reanahub/reana-job-controller/issues/238

cwl_reana: allows to use unpacked images

---

reana_workflow_engine_cwl/tasks.py

closes reanahub/reana-client#396

cli: parse operational options properly

---

reana_workflow_engine_cwl/cwl_reana.py

kubernetes: add support for voms_proxy

---

CHANGES.rst
README.rst
docs/conf.py
pytest.ini
reana_workflow_engine_cwl/__init__.py
reana_workflow_engine_cwl/config.py
reana_workflow_engine_cwl/context.py
reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/database.py
reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/pipeline.py
reana_workflow_engine_cwl/poll.py
reana_workflow_engine_cwl/tasks.py
run-tests.sh
setup.py
tests/test_version.py

global: Black support

---

.flake8
.github/workflows/ci.yml
Dockerfile
MANIFEST.in
reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/pipeline.py
run-tests.sh
setup.py

addresses https://github.com/reanahub/reana/issues/450

ci: add hadolint and flake8 linters

---

reana_workflow_engine_cwl/cwl_reana.py
reana_workflow_engine_cwl/main.py
reana_workflow_engine_cwl/tasks.py
requirements.txt
setup.py

* Uses REANA-Commons decorator to handle termination signals in the
workflow engine container by notifying the system about the failure
and registering the workflow as failed.
Addresses reanahub/reana#478

global: handle termination signals

---

reana_workflow_engine_cwl/version.py
requirements.txt
setup.py

release: 0.8.0a2

---

reana_workflow_engine_cwl/pipeline.py

closes https://github.com/reanahub/reana-workflow-engine-cwl/issues/196

cwl: improved output logging

---

reana_workflow_engine_cwl/version.py
requirements.txt
setup.py

- installation: bump shared modules
- release: 0.8.0a3

release 0.8.0a3

---

requirements.txt
setup.py

closes https://github.com/reanahub/reana-server/issues/442

installation: bump shared modules

---

CHANGES.rst
reana_workflow_engine_cwl/cwl_reana.py

closes https://github.com/reanahub/reana-job-controller/issues/206

slurm: expose some of the job configuration to users

---

CHANGES.rst
reana_workflow_engine_cwl/config.py
reana_workflow_engine_cwl/cwl_reana.py
requirements.txt
setup.py

add global Kerberos flag propagation

---

CHANGES.rst
reana_workflow_engine_cwl/version.py
requirements.txt
setup.py

- installation: bump shared modules
- installation: bump all dependencies
- release: 0.9.1

release: 0.9.1

---

CHANGES.rst
Dockerfile
reana_workflow_engine_cwl/version.py
requirements.txt
setup.py

release: 0.9.2

---

reana_workflow_engine_cwl/cwl_reana.py

Closes reanahub/reana-workflow-controller#546

fix(progress): handle stopped jobs (#260)
