reanahub/reana-workflow-engine-cwl

Dockerfile, MANIFEST.in, requirements-dev.txt
* Removes concrete `wdb` environment variables since them will be
provided by `reana-cluster` when running on dev mode (closes #23).
=> docker: set debug build flag

setup.py
* Pins cwltool and schema-salad to latest versions that work
with cwl conformance tests.
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
=> installation: pin cwltool and schema-salad

Dockerfile, reana_workflow_engine_cwl/tasks.py, requirements-dev.txt
* Removes reana-workflow-commons as a dependency as it is merged
with reana-commons.
Connects https://github.com/reanahub/reana-workflow-commons/issues/4
=> global: remove reana-workflow-commons

reana_workflow_engine_cwl/cwl_reana.py
* Docker image has always a default value as we force it, but some
some times the submited workflows do not require Docker even though
we are going to always run on Docker.
=> job-submission: always use docker

reana_workflow_engine_cwl/cwl_reana.py
This change looks for the `REANA_WORKFLOW_ENGINE_EXPERIMENT` env variable and uses its value for the `experiment` field when creating jobs.
I'm running reana in Openshift under a non-default namespace ("reana"), and I need the jobs created in the same namespace as the volume claims.
=> Fetches experiment name from environment

Dockerfile, reana_workflow_engine_cwl/config.py, reana_workflow_engine_cwl/cwl_reana.py, setup.py
* Adds list with cvmfs mounts in job spec.
* Updates the default SHARED_VOLUME_PATH to /var/reana.
Connects https://github.com/reanahub/reana-cluster/issues/131
=> cwl_reana: cvmfs mounts for jobs

reana_workflow_engine_cwl/cwl_reana.py, setup.py
* To enable cache R-J-C needs workflow uuid for getting
workspace path.
Connects reanahub/reana-job-controller/issues/118
=> cwl_reana: pass workflow uuid for R-J-C

Dockerfile
* Adds back Node.js dependency because `cwltool` requires it for handling
JavaScript extensions. Necessary for running certain CWL workflows.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> docker: addition of nodejs

reana_workflow_engine_cwl/tasks.py, setup.py
* When job controller and workflow engines run in the same pod,
workflow engine has to ensure that job controller is ready to
receive requests.
Connects reanahub/reana-job-controller/issues/105
=> tasks: adds connectivity to job controller check

reana_workflow_engine_cwl/tasks.py
* CWL workflows do not work with current master because RWC passes `--workflow-file`, which is not expected by RWECWL.
```
$ kubectl logs reana-batch-cwl-9ddddde2-e863-437a-9f97-d62758cd250e-ltwv4 workflow-engine
Usage: run-cwl-workflow [OPTIONS]
Try "run-cwl-workflow --help" for help.
Error: no such option: --workflow-file
```
* Addresses #133
=> tasks: adds flag for relative path to the workflow file

reana_workflow_engine_cwl/main.py
Problem:
Currently unable to restart a CWL workflow in the same workspace due to existing directories.
```
$ reana-client logs -w test-cwl-restart
==> Workflow engine logs
...
workflow failed: [Errno 17] File exists: '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1fc4c299-36ca-410e-93aa-9336037a936a/cwl/tmpdir'
```
Fix:
With this amend running a CWL workflow does not fail if the `cwl/tmpdir`, `cwl/outdir` and `cwl/docker_stagedir` already exist.
Consequences:
If you rerun the same workflow, output files may be overwritten in `cwl/docker_outdir`. It is the users responsibility to make sure the output name is unique. 
closes reanahub/reana-server#293
=> main: allow dir to exist, necessary for restart

CHANGES.rst, reana_workflow_engine_cwl/cwl_reana.py
Add `htcondor_max_runtime` and `htcondor_accounting_group` to CWL scheme
Closes reanahub/reana-job-controller#32
=> Add HTC resources

CHANGES.rst, reana_workflow_engine_cwl/cwl_reana.py
* Renames ``succeeded`` to ``finished`` as the latter is the one
described centrally in ``reana_db.models.WorkflowStatus`` and
``reana_db.models.JobStatus``.
=> global: rename job status succeeded

requirements.txt, setup.py
This PR removes `sqlalchemy` and `sqlalchemy-utils` from the list of project requirements. The list of `requirements.txt` has been updated accordingly.
Similar to https://github.com/reanahub/reana-workflow-engine-yadage/pull/182 PR.
=> installation: remove legacy sqlalchemy

CHANGES.rst, reana_workflow_engine_cwl/cwl_reana.py
- via kubernetes_memory_limit in hint of a job
closes reanahub/reana-client#496
=> k8s: allow customising job memory limit

AUTHORS.rst, reana_workflow_engine_cwl/main.py, requirements.txt, setup.py
Delete the dependency on SHARED_VOLUME_PATH by storing the full path inside the database, for serial, yadage and cwl engines.
Closes reanahub/reana-db#94
=> models: modify  workspace_path to store full path

reana_workflow_engine_cwl/cwl_reana.py, reana_workflow_engine_cwl/main.py, reana_workflow_engine_cwl/tasks.py
closes https://github.com/reanahub/reana-workflow-engine-cwl/issues/206
The internal format of parsed hints after the `cwltool` upgrade have changed. This PR addresses this issue to support `reana` hints again.
Also, running `reana-client run -f reana-cwl-slurmcern.yaml` locally created a workflow which got `finished`(instead of got `failed`), but with errors in the logs . This PR also fixes this issue by publishing the right workflow status in the end of execution.
Only thing which is unsolved is that now `cwltool` prints a warning about the unresolved `hints` that are coming from `reana`. They state this in CWL spec: https://www.commonwl.org/v1.2/Workflow.html#Requirements_and_hints
> A hint is similar to a requirement; however, it is not an error if an implementation cannot satisfy all …
=> main: support reana hints after cwltool upgrade

CHANGES.rst, reana_workflow_engine_cwl/cwl_reana.py, requirements.txt
closes reanahub/reana-job-controller#343
How to test:
This PR is part of a bigger group of PRs. Please refer to the addressed issue to see all of them.
1. Modify CWL helloworld example, with `kubernetes_job_timeout=20` (in seconds) and `sleeptime=2` (2 seconds so the workflow will definitely run longer than 20 seconds):
`workflow/cwl/helloworld-job.yml`
```yaml
sleeptime: 2
...
```
`workflow/cwl/helloworld.cwl`
```yaml
...
steps:
first:
hints:
reana:
kubernetes_job_timeout: 20  # <= here
run: helloworld.tool
...
```
2. Start workflow `reana-client run -w cwl-timeout -f reana-cwl.yaml`
3. After 25-30 seconds, check using `reana-client list` if workflow failed. It should.
4. Using `reana-client logs` check if the reason is `Job was killed due to timeout.`
5. Try to input string or object …
=> add kubernetes_job_timeout parameter

AUTHORS.rst, CHANGES.rst, reana_workflow_engine_cwl/cwl_reana.py
Closes reanahub/reana-auth-rucio#1.
=> cwl_reana: add rucio support

.readthedocs.yaml, MANIFEST.in, setup.py
=> docs: add .readthedocs.yaml to migrate to RTD v2

AUTHORS.md, reana_workflow_engine_cwl/cwl_reana.py
This pull request add support for user configurable parameters in the Compute4PUNCH backend. See https://github.com/reanahub/reana-job-controller/pull/430.
=> feat(api) Add support for the Compute4PUNCH backend

.github/workflows/ci.yml, setup.py
BREAKING CHANGE: drop support for Python 3.6 and 3.7
Closes reanahub/reana#784
=> build(python): drop support for Python 3.6 and 3.7 (#275)

.github/workflows/ci.yml, Dockerfile
Pin `setuptools` to the maximum version of 70 to allow working on Ubuntu 20.04 LTS based environments. (New versions of `setuptools` are not compatible.)
Note that this fix is necessary only for the `maint-0.9` branches and the REANA 0.9 release series. In `master` we have switched to Ubuntu 24.04 LTS based environments and Python 3.12 and no pinning is necessary there.
=> chore(docker): pin setuptools 70

AUTHORS.md, reana_workflow_engine_cwl/cwl_reana.py, requirements.txt, setup.py
=> feat(cwl_reana): pass resource requests/limits to job-controller
